### ISSUE TITLE
Cross-Platform Path Separatores in serveStatic

### ISSUE THREAD

**Issue by cawoodm** [cmorten/opine#145]
# Issue

Setup:

- deno 1.14.3 (release, x86_64-pc-windows-msvc)
- v8 9.4.146.19
- typescript 4.4.2
- Opine Version: 1.8.0

## Details

The path separator `\` for windows is inconsistently applied in `serveStatic.ts` and `send.ts`. In particular `hasTrailingSlash()` assumes `/` whereas the path which has been `normalize()` contains (and may end with) `\`.

![image](https://user-images.githubusercontent.com/498834/137377419-3a3725ef-a7ca-4e2c-87d2-485562733476.png)

**Comment by cmorten** [comment]
Hey @cawoodm 👋

I _think_ I've released a fix for this, but could have missed somewhere! Would you be able to check if you still have the same issues with `opine@2.0.2`?
