### ISSUE TITLE
Some (but not all) static files fail to be served - ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by jeremythille** [cmorten/opine#151]
# Issue

Setup:

- Deno Version: 1.17 (updated today)
- v8 Version: Not sure, the one shipped with Deno 1.17?
- Typescript Version: 4.5
- Opine Version: 2.0.0

## Details

I am using Opine to serve my Angular application's static files. Angular's "dist" folder contains :

```
- index.html (2.2 KB)
- main.js (182 KB, development version, un-minified)
- polyfill.js (44 KB)
- runtime.js (1 KB) 
- styles.css (7.7 KB)
```

My server code :
```
import { opine, serveStatic } from "https://deno.land/x/opine@2.0.0/mod.ts";
import { distDir } from "./utils.ts"

console.log(`distDir = `, distDir); // Logs "distDir =  D:\dev\Dwiki\front\dist", that's correct

const app = opine();

app.use(serveStatic(distDir)); 

app.get("/", (req, res) => res.sendFile(distDir + "/index.html"))

await app.listen(8090);

console.log(`App listening on http://localhost:8090`);
```

## Result :

When I  localhost:8090, some files get loaded, some don't :

```
- index.html (2.2 KB) --> OK 200
- main.js (182 KB) --> (failed)net::ERR_CONTENT_LENGTH_MISMATCH
- polyfill.js (44 KB)--> (failed)net::ERR_CONTENT_LENGTH_MISMATCH
- runtime.js (1 KB) --> OK 200
- styles.css ( 7.7 KB) --> OK 200
```
No error in the terminal or in the browser's console. All that's displayed in my terminal is : 

> distDir =  D:\dev\Dwiki\front\dist
> App listening on http://localhost:8090

If I serve my Angular app with `ng serve`, it displays correctly.

I can see the content of `index.html`, `runtime.js` and `styles.css` in the browser's network tab.
Not sure why some files are served correctly by Deno/Opine, and some (always these two) get `(failed)net::ERR_CONTENT_LENGTH_MISMATCH`

EDIT

I noticed the two files that fail to be served are also the two heaviest of the lot. I have updated my question, adding the weight of each file, above. It looks like small files (7 KB, 1 KB, 2 KB) are being served normally, but heavier files (44 KB, 182 KB) get  ERR_CONTENT_LENGTH_MISMATCH

**Comment by xyzshantaram** [comment]
@jeremythille Hi! I've run into the same issue, and I'm wondering if you've found a workaround yet -- this is kind of a deal breaker...

**Comment by jeremythille** [comment]
@ No, actually I tried to remove Opine altogether and serve my files just with Deno, without a library, and so far it works well

**Comment by cmorten** [comment]
Heya @xyzshantaram, @jeremythille 👋 

Do you have a minimal reproduceable example / gist / repo that I can use to try and debug this issue?

**Comment by jeremythille** [comment]
Ha, no sorry (and it's new year's eve, and then I'm going on a trip so I don't really have time to set up a repo now). But I've put my whole server code in my original question, apart from the Angular files which are really generic HTML/CSS/JS files. Thanks for looking into this issue, and of course, happy new year :)

**Comment by xyzshantaram** [comment]
@jeremythille That will work for a bit, I suppose.
@cmorten I can try to write one for you, it's a bit late where I am but I will try to post it by tomorrow!

**Comment by xyzshantaram** [comment]
@cmorten -- Here you go! https://github.com/xyzshantaram/opine-content-length-bug

**Comment by cmorten** [comment]
Thanks for the great repro @xyzshantaram!

I've identified the issue - with some of the changes moving to the new std/http server for `2.0.0` of opine a regression has been introduced where served files are now being closed before the stream has finished reading them.

![Problem code where resources are closed just after the respond call is made in response.ts](https://user-images.githubusercontent.com/11313985/147849270-c7ad15c9-3115-4c3d-b183-0550a02a9a82.png)

I have an idea for a fix which can look into this afternoon 😄

**Comment by cmorten** [comment]
Hey @jeremythille @xyzshantaram I've just released `2.0.2` which I believe fixes the issue. If not please do reopen!

**Comment by jeremythille** [comment]
Hi Craig, thanks for the follow-up and the quick maintenance. Will try to
test it later today or tomorrow. Cheers

**Comment by xyzshantaram** [comment]
Ah, crap, I forgot to respond to this! @cmorten thanks a lot for the prompt fix, it worked perfectly! <3
