### ISSUE TITLE
How to read a request received from a html form?

### ISSUE THREAD

**Issue by ClimenteA** [cmorten/opine#158]
I didn't figure it out how to process a request from an html form.

How a handler for this form would look like?

```html

<form action="/save" method="POST" enctype="multipart/form-data">

        <label for="somefield">
            Some field
            <input type="text" id="somefield" name="somefield" placeholder="somefield" required>
        </label>

        <label for="file">
            Upload
            <input type="file" id="file" name="file" required>
        </label> 

    <button type="submit">Save</button>

</form>

```

**Comment by asos-craigmorten** [comment]
There is currently no built-in way to parse `multipart/form-data` from an Opine server, you have to parse the `req.body` yourself in a custom middleware.

It should be reasonably straightforward to expose the `Request.formData()` API from the underlying `Request` object to achieve this.

Related: https://github.com/cmorten/opine/issues/159

**Comment by cmorten** [comment]
Closing this as a dupe in favour of #159
