### ISSUE TITLE
Deno.Buffer will be deprecated in Deno 2.0

### ISSUE THREAD

**Issue by yourfriendoss** [cmorten/opine#162]
Deno.Buffer should be replaced with [std/io/buffer](https://deno.land/std/io/buffer.ts) instead. Deno.Buffer is used in the bodyParser tests. This should probably be fixed once #161 is implemented.

**Comment by cmorten** [comment]
Removed in 5c388e9e5e0ac81c89bc255b7550ab21560ee79c
