### ISSUE TITLE
Type incompatibility with Deno 1.20.1

### ISSUE THREAD

**Issue by AEtheve** [cmorten/opine#164]
# Issue

Setup:

- Deno Version: 1.20.1
- v8 Version: 10.0.139.6
- Typescript Version: 4.6.2
- Opine Version: 2.1.4

## Details
There is a type incompatibility with Deno 1.20.1 for listenAndServeTls :
```
error: TS2345 [ERROR]: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.
          await server.listenAndServeTls(options.certFile, options.keyFile);
                                         ~~~~~~~~~~~~~~~~
    at ./src/application.ts

**Comment by AEtheve** [comment]
I fixed it temporarily by replacing 
`if (isTls) {` in application.ts
 with :
`if (isTls && typeof options.certFile == "string" && typeof options.keyFile == "string") {`

**Comment by cmorten** [comment]
Yeah seems types just slightly mismatching now.

ListenTlsOptions have all pertinent keys as optional https://doc.deno.land/deno/stable/~/Deno.ListenTlsOptions which is inherited by opine’s HTTPSOptions https://github.com/cmorten/opine/blob/main/src/types.ts#L22 so isTls isn’t quite cutting it anymore.

Think solution would be to adjust HTTPSOptions defined in opine’s types to have the key and cert keys as non-optional.

**Comment by AEtheve** [comment]
Ok, fine, that's what I thought, thanks.

**Comment by cawoodm** [comment]
Sorry, what's the fix here? I'm getting this error with opine 2.1.4 AFAIK the latest version.
