### ISSUE TITLE
Requested module doesn't provide required data

### ISSUE THREAD

**Issue by TigerbyteDev** [cmorten/opine#170]
# Issue

Setup:

- Deno Version: 1.23.3 (release, x86_64-unknown-linux-gnu)
- v8 Version: 10.4.132.8
- Typescript Version: 4.7.4
- Opine Version: 0.21.2

## Details
When importing the module, I'm getting the following error:
```
error: Uncaught SyntaxError: The requested module './FactorizeEvt.ts' does not provide an export named 'FactorizeEvt'
export { FactorizeEvt } from "./FactorizeEvt.ts";
         ^
    at <anonymous> (https://deno.land/x/evt@v1.8.7/lib/types/helper/index.ts:1:10)
```

**Comment by asos-craigmorten** [comment]
Hi @TigerbyteDev :wave:

The latest version of Opine is `2.2.0`, `0.21.2` is quite old and the `evt` package has long since been taken out of the dependencies. Try importing https://deno.land/x/opine@2.2.0 instead.
