### ISSUE TITLE
Request protocol for WebSocket upgrade request is always http

### ISSUE THREAD

**Issue by lvl-mattwells** [cmorten/opine#173]
# Issue

Setup:

- Deno Version: 1.31.3 (release, x86_64-pc-windows-msvc)
- v8 Version: 11.0.226.19
- Typescript Version: 4.9.4
- Opine Version: 2.2.0

## Details

Hello!

If I make a request using the browser's built-in WebSocket constructor like: `new WebSocket("ws://localhost:5555/ws")` I get `req.protocol = http` and `req.proto = ""`. What I would expect is that I would get `req.protocol = ws`, and `req.protocol = wss` for secure connections.

For repro you could probably add a `console.log(req.protocol)` to your [WebSockets example](https://github.com/cmorten/opine/blob/main/examples/websockets/server.ts#L49).

Any workarounds/suggestions would be appreciated! Thanks!

**Comment by cmorten** [comment]
Sorry taken a while to check notifications, this seems reasonable 🙂

**Comment by cmorten** [comment]
Actually, I don't believe this is what we want - the ws handshake is performed over HTTP so what you're seeing in Opine is that initial handshake request and the protocol is as expected.

Once the connection is established and the connection upgrade executed _then_ the ws protocol is used, but by this point we're no longer in the remit of Opine's request middleware, instead performing event handling on the connections themselves.

> The opening handshake is intended to be compatible with HTTP-based server-side software and intermediaries, so that a single port can be used by both HTTP clients talking to that server and WebSocket clients talking to that server. To this end, the WebSocket client's handshake is an HTTP Upgrade request

See https://www.rfc-editor.org/rfc/rfc6455.
