### ISSUE TITLE
[FEAT] Response lifecycle hooks

### ISSUE THREAD

**Issue by FaberVitale** [cmorten/opine#40]
# Issue

In node there are libraries like [on-headers](https://www.npmjs.com/package/on-headers) and [on-finished](https://www.npmjs.com/package/on-finished) that are commonly use to run logic  before and after a request has been processed, some example:

* [ morgan](https://github.com/expressjs/morgan/blob/master/index.js#L138)

* [session](https://github.com/expressjs/session/blob/master/index.js#L220)

It would be nice to port some of these projects to opine but it is not currently as easy as it should for a middleware to be called back when one of these events occurs:

1. Before`req.respond`: An async response is complete (e.g db returns output) and we are going to call [request.respond](https://github.com/asos-craigmorten/opine/blob/main/src/response.ts#L170).

2. After `req.respond`: A request has been processed and the response has been sent, essentially the output of `request.respond`.

# Suggested Changes

1. Add a getter that returns a lazily instantiated and cached promise that resolves before calling [request.respond](https://github.com/asos-craigmorten/opine/blob/main/src/response.ts#L170).

2. Add a getter that exposes the output of [request.respond](https://github.com/asos-craigmorten/opine/blob/main/src/response.ts#L171).

**Comment by asos-craigmorten** [comment]
Sounds good - think we should investigate whether either of these would be best implemented first in the std http library for Deno, but certainly wouldn’t be much work to add to Opine itself (either custom or hanging off of the std http methods).

I believe there is already a `done` or similar promise on the request object which could be used for one of these hooks?

**Comment by jly36963** [comment]
What was the decision on this? I'm wanting to write a response-time middleware in one of the following ways:
- [use events / lifecycle hooks](https://stackoverflow.com/a/68421619)
- [treat the middleware like a stack](https://github.com/oakserver/oak/blob/17d9e615825c9886f3ff7bbea7dd43f0a961e654/examples/proxyServer.ts#L70)

To log response-time in opine, is there a way to do the following without splitting the logic into two separate middlewares?
```js
app
  .use(getStart)
  .use(routes)
  .use(getFinishAndLogTimeDelta)
```

**Comment by asos-craigmorten** [comment]
@jly36963 no decision as such 🙃 issue remained unchanged and not worked on for over a year so closed as stale. If it's something you're keen on / have ideas on implementation then happy to reopen! 😄

**Comment by jly36963** [comment]
@asos-craigmorten If I can find a simple solution I'll open a PR 😄
